# Generated by Django 3.2.4 on 2021-06-30 08:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_avatar2, verbose_name='Avatar'),
        ),
    ]
